model:
  arch: "DM-LRN"
  max_channels: 256
  modulation: "SPADE"
  activation: ("LeakyReLU", [0.2, True] )
  upsample: "bilinear"
  use_crp: True
  criterion: (("LogDepthL1Loss",  1.0), )
  predict_log_depth: True
  mask_encoder_ksize: 3


  backbone:
    arch: "efficientnet-b0"
    imagenet: True
    norm_layer: ""
    multi_scale_output: True

train:
  batch_size: 32
  lr: 0.0001
