_BASE_: "Base-RCNN-FPN.yaml"
EVAL : False # TODO ---- eval ----


TRAIN_COCO_JSON : ["/project/3dlg-hcvc/mirrors/www/Mirror3D_final/nyu/with_mirror/precise/network_input_json/train_10_normal_mirror.json"] # TODO
TRAIN_IMG_ROOT : ["/project/3dlg-hcvc/mirrors/www/Mirror3D_final/nyu/with_mirror/precise"] # TODO
TRAIN_NAME : ["nyu_456_608_train"]
VAL_COCO_JSON : ["/project/3dlg-hcvc/mirrors/www/Mirror3D_final/nyu/with_mirror/precise/network_input_json/test_10_normal_mirror.json"] # TODO
VAL_IMG_ROOT : ["/project/3dlg-hcvc/mirrors/www/Mirror3D_final/nyu/with_mirror/precise"] # TODO
VAL_NAME : ["nyu_456_608_test"]
OUTPUT_DIR : "/project/3dlg-hcvc/jiaqit/checkpoint/mirror3d_net_output"


############## network configure ##############

MODEL:
  WEIGHTS : "/project/3dlg-hcvc/jiaqit/checkpoint/important_checkpoint/train_m3d_all_640_480_ransac_10_m3d_normal_all_640_480_ransac_2020-10-25-19-54-25/model_0072999.pth" # "./weight/R-50.pkl"
  DEVICE : "cuda:0" 
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE : (128) # set to largest
    NUM_CLASSES : 1 #  only predict mirror; one class 
  MASK_ON: True # mask_rcnn_R_50_FPN_1x
  RESNETS: # mask_rcnn_R_50_FPN_1x
    DEPTH: 50

TEST:
  EVAL_PERIOD: 100 # TODO
  AUG:
    ENABLED : False 

SOLVER:
  STEPS : (7000, 8000) # TODO
  MAX_ITER : (10000) # TODO
  IMS_PER_BATCH : 1 # TODO max 16
  BASE_LR : 1e-4 # TODO
  CHECKPOINT_PERIOD : 2000

DATALOADER:
  NUM_WORKERS : 1
  FILTER_EMPTY_ANNOTATIONS : True
  
INPUT:
  MIN_SIZE_TRAIN : (456,)
  MAX_SIZE_TRAIN : 608
  MIN_SIZE_TEST : (456)
  MAX_SIZE_TEST : 608

############## planeRCNN configure ##############
DEPTH_EST : False  # TODO ori & new(optional)
ANCHOR_REG : True  #! TODO ori & new
ANCHOR_CLS : True  #! TODO ori & new eval
OBJECT_SEG : True # TODO ori & new
OBJECT_CLS : True # TODO new 
OBJECT_BBOX_REG : True # TODO ori & new
RGBD_INPUT : False # TODO ori & new(optional)

# ---- DEPTH_EST -----
FOCAL_LENGTH : 519 # TODO
DEPTH_SHIFT : 1000.0 #! TODO eval
INVERSE_DEPTH : False 
REFINED_DEPTH : True #! TODO eval
MESH_DEPTH : True  

# ---- ANCHOR_REG -----
ANCHOR_REG_METHOD : 1  # TODO # (1) loss with GT residual (2) loss with GT normal  
UNIT_ANCHOR_NORMAL : True

# ---- ANCHOR_CLS -----
# during evaluation : evaluate img_size & f should be the same as MODEL.WEIGHTS's img_size & f
ANCHOR_NORMAL_NYP : "/local-scratch/share_data/mirror3D/m3d/m3d_all_normal/m3d_kmeans_normal_10.npy"  #! TODO 

#! ############# eval configure ##############
EVAL_ANCHOR_AP : False # TODO
EVAL_CLS_AP : False # TODO
EVAL_MASK_IOU : False
EVAL_NORMAL : False  # TODO angle diff & normal l2 loss
EVAL_BRANCH_ORI_DEPTH : False # TODO mirror3d_eval matrics
EVAL_BRANCH_REF_DEPTH : False # TODO mirror3d_eval matrics
EVAL_INPUT_REF_DEPTH : False # TODO REF_DEPTH_TO_REFINE
EVAL_HEIGHT : 456
EVAL_WIDTH : 608

# ---- eval output ----
EVAL_SAVE_MASKED_IMG : False # TODO 
EVAL_SAVE_NORMAL_VIS : False # TODO
EVAL_SAVE_DEPTH : True # TODO
MASK_ON_OTHER_SIZE : True

# --------- refine depth -----------
REF_DEPTH_TO_REFINE : "/project/3dlg-hcvc/jiaqit/cvpr/R1_rerun/saic_meshraw_color_mask_gtD_predD.txt" # TODO
REF_MODE : "DE_border" # TODO # "none / rawD_mirror / rawD_border / DE_mirror / DE_border " 
REF_BORDER_WIDTH : 50 # TODO









