_BASE_: "../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
EVAL : True # TODO ---- eval ----


# TRAIN_COCO_JSON : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/coco_input/nyu/m3d_kmeans_normal_10_only_mirror/pos_train_normalFormat_10_normal.json"] # TODO
TRAIN_COCO_JSON : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/coco_input/nyu/m3d_kmeans_normal_10_only_mirror/pos_train_normalFormat_10_normal.json"] # TODO
TRAIN_IMG_ROOT : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/nyu"] # TODO
TRAIN_NAME : ["DE_with_neg_456_608_train"]
# VAL_COCO_JSON : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/coco_input/nyu/m3d_kmeans_normal_10_only_mirror/pos_train_normalFormat_10_normal.json"] # TODO
VAL_COCO_JSON : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/coco_input/nyu/m3d_kmeans_normal_10_only_mirror/pos_test_normalFormat_10_normal.json"] # TODO
VAL_IMG_ROOT : ["/project/3dlg-hcvc/jiaqit/Mirror3D_dataset/nyu"] # TODO
VAL_NAME : ["DE_with_neg_456_608_test"]
OUTPUT_DIR : "/project/3dlg-hcvc/jiaqit/checkpoint/mirror3d_net_output/2021-01-09-21-40-39"

############## network configure ##############

MODEL:
  WEIGHTS : "/project/3dlg-hcvc/jiaqit/checkpoint/mirror3d_net_output/2021-01-09-21-40-39/2021-01-11-10-46-22/model_0051999.pth" # "./weight/R-50.pkl"
  DEVICE : "cuda:0" 
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE : (128) # set to largest
    NUM_CLASSES : 1 #  only predict mirror; one class 

TEST:
  EVAL_PERIOD: 1000 # TODO
  AUG:
    ENABLED : False 

SOLVER:
  STEPS : (7000, 8000) # TODO
  MAX_ITER : (100000) # TODO
  IMS_PER_BATCH : 4 # TODO max 16
  BASE_LR : 1e-4 # TODO
  CHECKPOINT_PERIOD : 2000

DATALOADER:
  NUM_WORKERS : 1
  FILTER_EMPTY_ANNOTATIONS : True
  
INPUT:
  MIN_SIZE_TRAIN : (456,)
  MAX_SIZE_TRAIN : 608
  MIN_SIZE_TEST : (456,)
  MAX_SIZE_TEST : 608

############## planeRCNN configure ##############
DEPTH_EST : False  # TODO ori & new(optional)
ANCHOR_REG : True  #! TODO ori & new
ANCHOR_CLS : True  #! TODO ori & new eval
OBJECT_SEG : True # TODO ori & new
OBJECT_CLS : False # TODO new 
OBJECT_BBOX_REG : True # TODO ori & new
RGBD_INPUT : False # TODO ori & new(optional)

# ---- DEPTH_EST -----
FOCAL_LENGTH : 519 # TODO
DEPTH_SHIFT : 1000.0 #! TODO eval
INVERSE_DEPTH : False 
REFINED_DEPTH : True #! TODO eval
MESH_DEPTH : True  

# ---- ANCHOR_REG -----
ANCHOR_REG_METHOD : 1  # TODO # (1) loss with GT residual (2) loss with GT normal  
UNIT_ANCHOR_NORMAL : True

# ---- ANCHOR_CLS -----
# during evaluation : evaluate img_size & f should be the same as MODEL.WEIGHTS's img_size & f
ANCHOR_NORMAL_NYP : "/local-scratch/share_data/mirror3D/m3d/m3d_all_normal/m3d_kmeans_normal_10.npy"  #! TODO 

#! ############# eval configure ##############
EVAL_ANCHOR_AP : True # TODO
EVAL_CLS_AP : True # TODO
EVAL_MASK_IOU : True
EVAL_NORMAL : True  # TODO angle diff & normal l2 loss
EVAL_BRANCH_ORI_DEPTH : False # TODO mirror3d_eval matrics
EVAL_BRANCH_REF_DEPTH : False # TODO mirror3d_eval matrics
EVAL_INPUT_REF_DEPTH : False # TODO REF_DEPTH_TO_REFINE
EVAL_HEIGHT : 456
EVAL_WIDTH : 608

# ---- eval output ----
EVAL_SAVE_MASKED_IMG : False # TODO 
EVAL_SAVE_NORMAL_VIS : False # TODO
EVAL_SAVE_DEPTH : False # TODO


# --------- refine depth -----------
REF_DEPTH_TO_REFINE : "" # TODO
REF_MODE : "DE_border" # TODO # "none / rawD_mirror / rawD_border / DE_mirror / DE_border " 
REF_BORDER_WIDTH : 50 # TODO









